[package]
name = "types"
version = "0.1.0"
authors = ["Pearce Keesling <pearce.keesling@lifeomic.com>"]
edition = "2018"

[dependencies]
ropey = "1.0.1"
notify = "4.0.12"
termion = "1.5.3"
generational-arena = "0.2.2"
