[package]
name = "core"
version = "0.1.0"
authors = ["Pearce Keesling <pearce.keesling@lifeomic.com>"]
edition = "2018"

[dependencies]
libloading = "0.5.1"
notify = "4.0.12"
types = { path = "../types" }
ropey = "1.0.1"
termion = "1.5.3"
crossbeam-channel = "0.3.8"
